### ISSUE TITLE
Error every time a command is sent

### ISSUE THREAD

**Issue by ryancasler** [tripplet/hyperionESPNode#1]
I get the following error every time I issue a command.

PANIC: unprotected error in call to Lua API (?:0: attempt to index global 'sjson' (a nil value))

**Comment by tripplet** [comment]
The firmware is to old, I forgot to update it in this repository but you can simply build one here:
https://nodemcu-build.com, just make sure to add sjson, ws2812, mdns and mqtt to the default selection.
